### ISSUE TITLE
How can we do more advanced things?

### ISSUE THREAD

**Issue by T-vK** [snappy46/GuitarixMidiController#1]
Hey, I just stumbled across this great project and I was trying to add some more advanced features. For instance, I want to control the Looper module in Guitarix from the Arduino. But I just can't figure out how to properly send the required messages and I also don't really understand how I have to set up Guitarix in order to make this work. 
By clicking with the Middle mouse button on the "REC" button in the Live Looper, I was able to specify a "MIDI Controller Number". I'm not sure what that is, but I think it's what you called "channel" in the code. Well, I just tried:

```
const byte MIDI_CHANNEL = 0x00;
const byte LOOPER_START_RECORD = 0x00;
controlChange(MIDI_CHANNEL, 0X20, LOOPER_START_RECORD);
MidiUSB.flush();
```

I also tried it with `LOOPER_START_RECORD = 0x01;`, but nothing happens in Guitarix when I run it..

Have you done anything like that before?

**Comment by snappy46** [comment]
Hi T-vK,

Yes I have the program to do that but wanted to clean up the code first and create new README file.  I haven't had the chance to do that; I have been very busy lately and injured my shoulder about 3 months ago and haven't been able to play the guitar since then ... therefore this project was not a priority.

Anyhow I pushed to the development branch what I have done to program one of the switch (1) to functioned with guitarix loop.  Basically press the switch once it will record, press again to stop, press once more to play ... I think!!! it's been a while since I played with it.

Hope this help you get going with that.

**Comment by T-vK** [comment]
Awesome! You're the best!  

These seem to be the interesting lines:

```
controlChange(channel, 0X29, 0X00); // stop playing
controlChange(channel, 0X29, 0X40); // start playing
controlChange(channel, 0X28, 0X40); // start recording
controlChange(channel, 0X28, 0X00); // stop recording
```

Can you give a short explanation on the parameters? Do I have to enter them somewhere in Guitarix? Or are these numbers preset in Guitarix or part of a standard or something? (If so, how did you figure out which codes were necessary?)

**Comment by snappy46** [comment]
Sorry I forgot about guitarix settings.  Basically in my case I setup the record button to 40 -> 0X28 and the play button to 41 -> 0x29 using midi setup for that plugin (Mid button).  I just double check the current sequence which is press once = record; press again = play, press again = stop.  Not exactly a full blown looper but that functionality works for me.  There's lots of room for improvement; currently there isn't a way to playback what was previously recorded.  If you press the button a forth time then it records again.  Using a different switch for the record and play function would solve that problem if this is an issue for you.  I cannot remember why I actually picked those control numbers; a lot of it is just trial and error. :(.

**Comment by T-vK** [comment]
Thank you so much! :) 
Yeah, it's not perfect, but it will do for now.  
I've been wondering if it would be possible to set it up like a normal single button looper pedal where you can record multiple layers and every layer you add automatically stops recording so that all layers have the exact same length. I think they usually also allow double press to delete the last layer and long press to reset everything. I haven't actually owned one, but the idea sound pretty good to me. 
It would be kind of weird and difficult to get that behavior with Guitarix's looper module though, I think.

**Comment by snappy46** [comment]
Well there are 4 tapes in the live looper so my guess would be that if you select a different one and go thru the process again it might work???  There's also some button libraries that provides detection of click, doulble click and long click so this should help.  Sounds like an interesting project.  Best of luck.

**Comment by snappy46** [comment]
Just has a quick look you cannot select the various Tapes using midi but every REC/PLAY button on each of them can be controllled by a different control number.  So Tape2 REC/PLAY could be controlled by 43, 44; Tape3 REC/PLAY 45, 46 ... etc....

**Comment by T-vK** [comment]
That's really good to know. 
I'm not too worried about the double/long click detection. I think the most difficult thing will be to perfectly time each tape to have the same recording length and to actually play in sync with each other. 
But I will try my best to get it to work and repirt back if I got somwthing.  
Thanks again for your help and the quick replies, I really appreciate it. :)

**Comment by snappy46** [comment]
Your welcome.

**Comment by T-vK** [comment]
I tried to implement the idea of the single button looper that I explained above. It seems to work, but my Arduino kept disconnecting and then I managed to rip out the USB port xD... Well, I guess I'll have to order a new one or try to fix that one for now.  
Anyway, here is the project: https://github.com/T-vK/Guitarix-Looper Feel free to copy whatever you want.
